---
- name: "Customising Kali"
  hosts: localhost
  vars:
    user: "{{ lookup('ansible.builtin.env', 'USER') }}"
    firefox_addons:
      - foxyproxy-standard
      - darkreader
      - wappalyzer
      - user-agent-string-switcher
  connection: local
  roles:
    - role: install_tools
    - role: config_tools
