---
- name: "Customising Kali"
  hosts: localhost
  connection: local
  tasks:
    - name: "Test"
      ansible.builtin.debug:
        msg: "Testing Hacker Playbook"
    - name: "Webapp tools installation"
      ansible.builtin.apt:
        pkg:
          - dmitry
          - wpscan
          - whatweb
          - nuclei
          - o-saft
          - tlssled
          - uniscan
          - wig
          - wafw00f
      become: true
