---
- name: "Customising Kali"
  hosts: localhost
  vars:
    user: "{{ lookup('ansible.builtin.env', 'USER') }}"
  connection: local
  tasks:
    - name: "Test"
      ansible.builtin.debug:
        msg: "Testing Hacker Playbook"
    - name: "Webapp tools installation"
      ansible.builtin.apt:
        pkg:
          - dmitry
          - wpscan
          - whatweb
          - nuclei
          - o-saft
          - tlssled
          - uniscan
          - wig
          - wafw00f
      become: true

    - name: "Set user that ran the playbook as owner of /opt"
      ansible.builtin.file:
        owner: "{{ user }}"
        group: "{{ user }}"
        path: /opt

    - name: "Download Algo source"
      ansible.builtin.git:
        repo: https://github.com/trailofbits/algo.git
        dest: /opt/Algo-source
        version: master

    - name: "Dependencies for Algo"
      ansible.builtin.apt:
        pkg:
          - resolvconf
      become: true

    - name: "Algo python dependencies"
      ansible.builtin.shell:
        cmd: cd /opt/Algo-source && python3 -m virtualenv --python="$(command -v python3)" .env \
             && source .env/bin/activate \
             && python3 -m pip install -U pip virtualenv \
             && python3 -m pip install -r requirements.txt
        creates: /opt/Algo-source/.env/libs/ansible
