---
# tasks file for config_tools
- name: "Install firefox addons"
  ansible.builtin.template:
    src: "policies.json.j2"
    dest: "/usr/lib/firefox-esr/distribution/policies.json"
    mode: '644'
  become: true
  become_method: sudo
