---
- name: "Check for CA Certificate"
  ansible.builtin.stat:
    path: /usr/share/ca-certificates/Burp_cacert.der
  register: burp_cert

- name: "Retrieve Burp CA Certificate"
  ansible.builtin.shell: |
    timeout 40 /usr/lib/jvm/java-17-openjdk-amd64/bin/java -Djava.awt.headless=true -jar /usr/share/burpsuite/burpsuite.jar \
    < <(yes) & sleep 30 \
    ; curl http://127.0.0.1:8080/cert -o /tmp/cacert.der
  args:
    executable: /bin/bash
  when: not burp_cert.stat.exists

- name: "Move Certificate to /usr/share/ca-certificates"
  ansible.builtin.copy:
    src: /tmp/cacert.der
    dest: /usr/share/ca-certificates/Burp_cacert.der
    owner: root
    group: root
    mode: 0644
  when: not burp_cert.stat.exists
  become: true
  become_method: sudo

- name: "Install firefox addons / certificates"
  ansible.builtin.template:
    # use this template file
    src: "policies.json.j2"
    # replace template contents and place at this location
    dest: "/usr/lib/firefox-esr/distribution/policies.json"
    # file permissions at destination are -rw-r--r--
    mode: '644'
  become: true
  become_method: sudo

- name: "Configure burp user settings"
  ansible.builtin.template:
    src: "UserConfigCommunity.json.j2"
    dest: "/home/{{ user }}/.BurpSuite/UserConfigCommunity.json"
