---
- name: "Installation of Web Application testing tools"
  ansible.builtin.apt:
    pkg:
      - dmitry
      - wpscan
      - whatweb
      - nuclei
      - o-saft
      - tlssled
      - uniscan
      - wig
      - wafw00f
      - feroxbuster
    # update apt package cache(apt update) before installing tools
    update_cache: true
  become: true
  become_method: sudo

- name: "Download Algo source"
  ansible.builtin.git:
    repo: https://github.com/trailofbits/algo.git
    dest: /opt/Algo-source
    # download source from the master branch
    version: master
  become: true
  become_method: sudo

- name: "Dependencies for Algo"
  ansible.builtin.apt:
    pkg:
      - resolvconf
      - python3-virtualenv
    # Do not install suggested packages
    install_recommends: false
    update_cache: true
  become: true
  become_method: sudo

- name: "Algo python dependencies"
  ansible.builtin.shell: |
    cd /opt/Algo-source && python3 -m virtualenv --python="$(command -v python3)" .env \
    && source .env/bin/activate \
    && python3 -m pip install -U pip virtualenv \
    && python3 -m pip install -r requirements.txt
  args:
    executable: /bin/bash
    creates: /opt/Algo-source/.env
  become: true
  become_method: sudo

- name: "Install Jruby and Jython for Burp Suite Extensions"
  ansible.builtin.apt:
    pkg:
      - jython
      - jruby
    update_cache: true
  become: true
  become_method: sudo

- name: "Download Nessus .deb"
  ansible.builtin.get_url:
    url: https://www.tenable.com/downloads/api/v2/pages/nessus/files/Nessus-10.5.3-debian10_amd64.deb
    dest: /home/{{ user }}/Downloads
    checksum: sha256:7a757b41deafc79b4aebb3c23305990b9ffb4f5aee1b59bfface7d3c7e27a2bb

- name: "Install nessus"
  ansible.builtin.apt:
    deb: /home/{{ user }}/Downloads/Nessus-10.5.3-debian10_amd64.deb
  become: true
  become_method: sudo

- name: "Clone Vulnerability Assessment Script from Adams GitHub"
  ansible.builtin.git:
    repo: https://github.com/Adam-board/Vulnerability-Assessment-Script.git
    dest: /opt/Vulnerability-Assessment-Script
    # download source from the master branch
    version: main
  become: true
  become_method: sudo
